-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 14:15:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema works
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `works` ;

-- -----------------------------------------------------
-- Schema works
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `works` DEFAULT CHARACTER SET utf8mb4 ;
USE `works` ;

-- -----------------------------------------------------
-- Table `works`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`department` ;

CREATE TABLE IF NOT EXISTS `works`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(8) NOT NULL,
  `parent` INT NULL,
  `about` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_fk_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `parent_fk`
    FOREIGN KEY (`parent`)
    REFERENCES `works`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `works`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`doctor` ;

CREATE TABLE IF NOT EXISTS `works`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(8) NOT NULL,
  `department` INT NULL,
  `level` ENUM('住院医师', '主治医师', '副主任医师', '主任医师') NOT NULL DEFAULT '住院医师',
  PRIMARY KEY (`id`),
  INDEX `dokcer_fk_department_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `dokcer_fk_department`
    FOREIGN KEY (`department`)
    REFERENCES `works`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `works`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`patient` ;

CREATE TABLE IF NOT EXISTS `works`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL,
  `id_card` CHAR(18) NOT NULL,
  `phone` CHAR(11) NOT NULL,
  `state` ENUM('正常', '注销') NOT NULL DEFAULT '正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `works`.`clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`clinic` ;

CREATE TABLE IF NOT EXISTS `works`.`clinic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(8) NOT NULL,
  `fees` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `works`.`scheduling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`scheduling` ;

CREATE TABLE IF NOT EXISTS `works`.`scheduling` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doctor` INT NOT NULL,
  `time` DATE NOT NULL,
  `clinic` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `scheduling_fk_doctor_idx` (`doctor` ASC) VISIBLE,
  INDEX `scheduling_fk_clinic_idx` (`clinic` ASC) VISIBLE,
  CONSTRAINT `scheduling_fk_doctor`
    FOREIGN KEY (`doctor`)
    REFERENCES `works`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scheduling_fk_clinic`
    FOREIGN KEY (`clinic`)
    REFERENCES `works`.`clinic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `works`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `works`.`appointment` ;

CREATE TABLE IF NOT EXISTS `works`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NOT NULL,
  `doctor` INT NOT NULL,
  `time` DATE NOT NULL,
  `num` INT NOT NULL,
  `clinic` VARCHAR(8) NOT NULL,
  `fees` INT NOT NULL,
  `generate` DATETIME NOT NULL DEFAULT now(),
  `state` ENUM('预约', '取消') NOT NULL DEFAULT '预约',
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `fk_patient`
    FOREIGN KEY (`patient`)
    REFERENCES `works`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor`
    FOREIGN KEY (`doctor`)
    REFERENCES `works`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
